[package]
name = "are-cli"
version = "0.1.0"
authors = ["trevorlink <lvpidadiao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "4.1.0"
redis = "0.10.0"
clap = "~2.33"